### ISSUE TITLE
Try removing threshholded maps

### ISSUE THREAD

**Issue by bcipolli** [bcipolli/OHBM-2016#8]
One map is always like this. I was never sure of what it meant; now I think it's due to threshholded maps.

![r_l_11](https://cloud.githubusercontent.com/assets/4072455/12007747/e1631dc0-abc7-11e5-81f9-a7d25515742c.png)

**Comment by atsuch** [comment]
Or it could have been due to the stat maps done on parcellated brains, like in this collection http://neurovault.org/collections/1003/

Manually removing a few problematic collections and applying filter to remove thresholded images did the trick. We don't get this weird-looking component any more!

**Comment by bcipolli** [comment]
Nice job!
